spring:
  application:
    name: upload-ms
  main:
    banner-mode: off
  threads:
    virtual:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
server:
  port: 8082
