quarkus.http.port=8082
quarkus.flyway.default-schema=file_upload
quarkus.flyway.migrate-at-start=true
quarkus.hibernate-orm.schema-management.strategy=validate
quarkus.http.auth.basic=true
quarkus.http.auth.basic.realm=file-upload-ms
quarkus.security.users.embedded.enabled=true
quarkus.security.users.embedded.plain-text=true
quarkus.security.users.embedded.users.user=user
quarkus.security.users.embedded.roles.test=user
quarkus.security.users.embedded.users.admin=admin
quarkus.security.users.embedded.roles.admin=admin
