%dev.quarkus.http.port=8082
%dev.quarkus.hibernate-orm.log.sql=true
%dev.quarkus.datasource.username=dev
%dev.quarkus.datasource.password=dev
%dev.quarkus.datasource.jdbc.url=jdbc:h2:mem:devDb
%dev.quarkus.datasource.db-kind=h2
%dev.quarkus.hibernate-orm.schema-management.create-schemas=true
%dev.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
