CREATE TABLE file_upload.user_file
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_uuid         VARCHAR(255)                            UNIQUE NOT NULL,
    file_name         VARCHAR(255)                            NOT NULL,
    url               VARCHAR(1024),
    file_data         BYTEA                                     NULL,
    file_content_type VARCHAR(255)                            NOT NULL,
    user_name         VARCHAR(255)                            NOT NULL,
    uploaded_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    upload_status     VARCHAR(255)                            NOT NULL,
    expiration_date   TIMESTAMP WITHOUT TIME ZONE,
    created_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL
);