CREATE TABLE file_upload.user_file
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_name     VARCHAR(255)                            NOT NULL,
    file_date     OID                                     NOT NULL,
    user_name     VARCHAR(255)                            NOT NULL,
    uploaded_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    upload_status VARCHAR(255)                            NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_userfile PRIMARY KEY (id)
);